services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: wget --spider --quiet http://localhost:3000/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "9060:80"
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    driver: bridge
